package bank_gui;

import bank_domain.Bank;

import javax.swing.*;
import java.awt.*;

public class BankGUI {
    private JPanel bankView;
    private JPanel knoppenbalk;
    private JPanel debitTransacties;
    private JPanel maakOver;
    private JPanel creditTransacties;
    private JButton debitOpnemen;
    private JButton debitStorten;
    private JButton overmaken;
    private JButton creditOpnemen;
    private JButton creditStorten;
    private JPanel zoeken;
    private JButton debitZoeken;
    private JButton creditZoeken;
    private JPanel debit;
    private JPanel credit;

    private Bank bank;

    public BankGUI(Bank bank) {
        this.bank = bank;
        System.out.println("Bank GUI Initiated!");
        JFrame frame = new JFrame("Hols bank");
        frame.setContentPane(bankView);
        frame.setBounds(800, 300, 800, 300);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        bankView = new JPanel();
        bankView.setLayout(new BorderLayout(0, 0));
        knoppenbalk = new JPanel();
        knoppenbalk.setLayout(new BorderLayout(0, 0));
        bankView.add(knoppenbalk, BorderLayout.SOUTH);
        debitTransacties = new JPanel();
        debitTransacties.setLayout(new BorderLayout(0, 0));
        knoppenbalk.add(debitTransacties, BorderLayout.WEST);
        debitOpnemen = new JButton();
        debitOpnemen.setText("Opnemen");
        debitTransacties.add(debitOpnemen, BorderLayout.WEST);
        debitStorten = new JButton();
        debitStorten.setText("Button");
        debitTransacties.add(debitStorten, BorderLayout.EAST);
        maakOver = new JPanel();
        maakOver.setLayout(new BorderLayout(0, 0));
        knoppenbalk.add(maakOver, BorderLayout.NORTH);
        overmaken = new JButton();
        overmaken.setText("Maak over >>");
        maakOver.add(overmaken, BorderLayout.CENTER);
        creditTransacties = new JPanel();
        creditTransacties.setLayout(new BorderLayout(0, 0));
        knoppenbalk.add(creditTransacties, BorderLayout.EAST);
        creditOpnemen = new JButton();
        creditOpnemen.setText("Opnemen");
        creditTransacties.add(creditOpnemen, BorderLayout.CENTER);
        creditStorten = new JButton();
        creditStorten.setText("Storten");
        creditTransacties.add(creditStorten, BorderLayout.EAST);
        zoeken = new JPanel();
        zoeken.setLayout(new BorderLayout(0, 0));
        knoppenbalk.add(zoeken, BorderLayout.CENTER);
        debitZoeken = new JButton();
        debitZoeken.setText("Zoeken");
        zoeken.add(debitZoeken, BorderLayout.WEST);
        creditZoeken = new JButton();
        creditZoeken.setText("Zoeken");
        zoeken.add(creditZoeken, BorderLayout.EAST);
        debit = new JPanel();
        debit.setLayout(new BorderLayout(0, 0));
        bankView.add(debit, BorderLayout.WEST);
        credit = new JPanel();
        credit.setLayout(new BorderLayout(0, 0));
        bankView.add(credit, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return bankView;
    }
}
